REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM oms_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM oms_app;
REVOKE USAGE ON SCHEMA public FROM oms_app;
DROP ROLE IF EXISTS oms_app;
