DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'oms_app') THEN
        CREATE ROLE oms_app WITH LOGIN PASSWORD 'oms' NOSUPERUSER NOBYPASSRLS;
    END IF;
END$$;

GRANT CONNECT ON DATABASE oms TO oms_app;
GRANT USAGE ON SCHEMA public TO oms_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO oms_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO oms_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO oms_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO oms_app;
